onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider R8
add wave -noupdate -group {Control Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/CONTROL_PATH/clk
add wave -noupdate -group {Control Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/CONTROL_PATH/rst
add wave -noupdate -group {Control Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/CONTROL_PATH/uins
add wave -noupdate -group {Control Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/CONTROL_PATH/flag
add wave -noupdate -group {Control Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/CONTROL_PATH/ir
add wave -noupdate -group {Control Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/CONTROL_PATH/currentState
add wave -noupdate -group {Control Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/CONTROL_PATH/nextState
add wave -noupdate -group {Control Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/CONTROL_PATH/decodedInstruction
add wave -noupdate -group {Control Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/CONTROL_PATH/instructionFormat1
add wave -noupdate -group {Control Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/CONTROL_PATH/instructionFormat2
add wave -noupdate -group {Control Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/CONTROL_PATH/overflowFlag
add wave -noupdate -group {Control Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/CONTROL_PATH/carryFlag
add wave -noupdate -group {Control Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/CONTROL_PATH/zeroFlag
add wave -noupdate -group {Control Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/CONTROL_PATH/negativeFlag
add wave -noupdate -radix hexadecimal -childformat {{/uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(0) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(1) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(2) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(3) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(4) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(5) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(6) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(7) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(8) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(9) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(10) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(11) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(12) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(13) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(14) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(15) -radix hexadecimal}} -subitemconfig {/uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(0) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(1) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(2) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(3) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(4) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(5) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(6) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(7) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(8) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(9) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(10) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(11) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(12) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(13) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(14) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg(15) {-height 15 -radix hexadecimal}} /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/REGISTER_FILE/reg
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/clk
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/rst
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/address
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/data_in
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/data_out
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/uins
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/instruction
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/flag
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/pc
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/sp
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/ir
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/rA
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/rB
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/ralu
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/dtReg
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/dtPC
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/dtSP
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/opA
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/opB
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/carryFlag
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/negativeFlag
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/zeroFlag
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/overflowFlag
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/s1
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/s2
add wave -noupdate -group {Data Path} -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/DATA_PATH/outALU
add wave -noupdate -divider Ports
add wave -noupdate -radix hexadecimal -childformat {{/uc_r8_tb/MICROCONTROLADOR/addressR8(15) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/addressR8(14) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/addressR8(13) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/addressR8(12) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/addressR8(11) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/addressR8(10) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/addressR8(9) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/addressR8(8) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/addressR8(7) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/addressR8(6) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/addressR8(5) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/addressR8(4) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/addressR8(3) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/addressR8(2) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/addressR8(1) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/addressR8(0) -radix hexadecimal}} -subitemconfig {/uc_r8_tb/MICROCONTROLADOR/addressR8(15) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/addressR8(14) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/addressR8(13) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/addressR8(12) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/addressR8(11) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/addressR8(10) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/addressR8(9) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/addressR8(8) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/addressR8(7) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/addressR8(6) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/addressR8(5) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/addressR8(4) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/addressR8(3) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/addressR8(2) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/addressR8(1) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/addressR8(0) {-height 15 -radix hexadecimal}} /uc_r8_tb/MICROCONTROLADOR/addressR8
add wave -noupdate -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/dataBus
add wave -noupdate -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/dataR8
add wave -noupdate -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/port_a
add wave -noupdate -group A -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/clk
add wave -noupdate -group A -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/rst
add wave -noupdate -group A -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/data
add wave -noupdate -group A -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/address
add wave -noupdate -group A -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/ce
add wave -noupdate -group A -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/rw
add wave -noupdate -group A -radix hexadecimal -childformat {{/uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(15) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(14) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(13) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(12) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(11) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(10) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(9) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(8) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(7) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(6) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(5) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(4) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(3) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(2) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(1) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(0) -radix hexadecimal}} -subitemconfig {/uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(15) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(14) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(13) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(12) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(11) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(10) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(9) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(8) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(7) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(6) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(5) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(4) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(3) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(2) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(1) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io(0) {-height 15 -radix hexadecimal}} /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_io
add wave -noupdate -group A -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/BIPORT_A/port_config
add wave -noupdate -group B -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/clk
add wave -noupdate -group B -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/rst
add wave -noupdate -group B -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/data
add wave -noupdate -group B -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/address
add wave -noupdate -group B -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/ce
add wave -noupdate -group B -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/rw
add wave -noupdate -group B -radix hexadecimal -childformat {{/uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(15) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(14) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(13) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(12) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(11) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(10) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(9) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(8) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(7) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(6) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(5) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(4) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(3) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(2) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(1) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(0) -radix hexadecimal}} -subitemconfig {/uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(15) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(14) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(13) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(12) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(11) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(10) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(9) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(8) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(7) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(6) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(5) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(4) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(3) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(2) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(1) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config(0) {-height 15 -radix hexadecimal}} /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_config
add wave -noupdate -group B -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/BIPORT_B/port_io
add wave -noupdate -expand -group Synthesizer -radix hexadecimal /uc_r8_tb/SYNTHESIZER/rst
add wave -noupdate -expand -group Synthesizer -radix hexadecimal /uc_r8_tb/SYNTHESIZER/A
add wave -noupdate -expand -group Synthesizer -radix hexadecimal /uc_r8_tb/SYNTHESIZER/SBY
add wave -noupdate -expand -group Synthesizer -radix hexadecimal /uc_r8_tb/SYNTHESIZER/ALD
add wave -noupdate -expand -group Synthesizer -radix hexadecimal -childformat {{/uc_r8_tb/SYNTHESIZER/allophone(7) -radix hexadecimal} {/uc_r8_tb/SYNTHESIZER/allophone(6) -radix hexadecimal} {/uc_r8_tb/SYNTHESIZER/allophone(5) -radix hexadecimal} {/uc_r8_tb/SYNTHESIZER/allophone(4) -radix hexadecimal} {/uc_r8_tb/SYNTHESIZER/allophone(3) -radix hexadecimal} {/uc_r8_tb/SYNTHESIZER/allophone(2) -radix hexadecimal} {/uc_r8_tb/SYNTHESIZER/allophone(1) -radix hexadecimal} {/uc_r8_tb/SYNTHESIZER/allophone(0) -radix hexadecimal}} -subitemconfig {/uc_r8_tb/SYNTHESIZER/allophone(7) {-height 15 -radix hexadecimal} /uc_r8_tb/SYNTHESIZER/allophone(6) {-height 15 -radix hexadecimal} /uc_r8_tb/SYNTHESIZER/allophone(5) {-height 15 -radix hexadecimal} /uc_r8_tb/SYNTHESIZER/allophone(4) {-height 15 -radix hexadecimal} /uc_r8_tb/SYNTHESIZER/allophone(3) {-height 15 -radix hexadecimal} /uc_r8_tb/SYNTHESIZER/allophone(2) {-height 15 -radix hexadecimal} /uc_r8_tb/SYNTHESIZER/allophone(1) {-height 15 -radix hexadecimal} /uc_r8_tb/SYNTHESIZER/allophone(0) {-height 15 -radix hexadecimal}} /uc_r8_tb/SYNTHESIZER/allophone
add wave -noupdate -group Input_Peripheral -radix hexadecimal -childformat {{/uc_r8_tb/INPUT_PERIPHERAL/data(15) -radix hexadecimal} {/uc_r8_tb/INPUT_PERIPHERAL/data(14) -radix hexadecimal} {/uc_r8_tb/INPUT_PERIPHERAL/data(13) -radix hexadecimal} {/uc_r8_tb/INPUT_PERIPHERAL/data(12) -radix hexadecimal} {/uc_r8_tb/INPUT_PERIPHERAL/data(11) -radix hexadecimal} {/uc_r8_tb/INPUT_PERIPHERAL/data(10) -radix hexadecimal} {/uc_r8_tb/INPUT_PERIPHERAL/data(9) -radix hexadecimal} {/uc_r8_tb/INPUT_PERIPHERAL/data(8) -radix hexadecimal} {/uc_r8_tb/INPUT_PERIPHERAL/data(7) -radix hexadecimal} {/uc_r8_tb/INPUT_PERIPHERAL/data(6) -radix hexadecimal} {/uc_r8_tb/INPUT_PERIPHERAL/data(5) -radix hexadecimal} {/uc_r8_tb/INPUT_PERIPHERAL/data(4) -radix hexadecimal} {/uc_r8_tb/INPUT_PERIPHERAL/data(3) -radix hexadecimal} {/uc_r8_tb/INPUT_PERIPHERAL/data(2) -radix hexadecimal} {/uc_r8_tb/INPUT_PERIPHERAL/data(1) -radix hexadecimal} {/uc_r8_tb/INPUT_PERIPHERAL/data(0) -radix hexadecimal}} -subitemconfig {/uc_r8_tb/INPUT_PERIPHERAL/data(15) {-height 15 -radix hexadecimal} /uc_r8_tb/INPUT_PERIPHERAL/data(14) {-height 15 -radix hexadecimal} /uc_r8_tb/INPUT_PERIPHERAL/data(13) {-height 15 -radix hexadecimal} /uc_r8_tb/INPUT_PERIPHERAL/data(12) {-height 15 -radix hexadecimal} /uc_r8_tb/INPUT_PERIPHERAL/data(11) {-height 15 -radix hexadecimal} /uc_r8_tb/INPUT_PERIPHERAL/data(10) {-height 15 -radix hexadecimal} /uc_r8_tb/INPUT_PERIPHERAL/data(9) {-height 15 -radix hexadecimal} /uc_r8_tb/INPUT_PERIPHERAL/data(8) {-height 15 -radix hexadecimal} /uc_r8_tb/INPUT_PERIPHERAL/data(7) {-height 15 -radix hexadecimal} /uc_r8_tb/INPUT_PERIPHERAL/data(6) {-height 15 -radix hexadecimal} /uc_r8_tb/INPUT_PERIPHERAL/data(5) {-height 15 -radix hexadecimal} /uc_r8_tb/INPUT_PERIPHERAL/data(4) {-height 15 -radix hexadecimal} /uc_r8_tb/INPUT_PERIPHERAL/data(3) {-height 15 -radix hexadecimal} /uc_r8_tb/INPUT_PERIPHERAL/data(2) {-height 15 -radix hexadecimal} /uc_r8_tb/INPUT_PERIPHERAL/data(1) {-height 15 -radix hexadecimal} /uc_r8_tb/INPUT_PERIPHERAL/data(0) {-height 15 -radix hexadecimal}} /uc_r8_tb/INPUT_PERIPHERAL/data
add wave -noupdate -group Input_Peripheral -radix hexadecimal /uc_r8_tb/INPUT_PERIPHERAL/data_av
add wave -noupdate -group Input_Peripheral -radix hexadecimal /uc_r8_tb/INPUT_PERIPHERAL/data_ack
add wave -noupdate -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/CONTROL_PATH/decodedInstruction
add wave -noupdate -divider R8
add wave -noupdate -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/clk
add wave -noupdate -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/rst
add wave -noupdate -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/data_in
add wave -noupdate -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/data_out
add wave -noupdate -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/address
add wave -noupdate -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/ce
add wave -noupdate -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/rw
add wave -noupdate -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/R8/flag
add wave -noupdate -radix hexadecimal -childformat {{/uc_r8_tb/MICROCONTROLADOR/R8/uins.mPC -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/uins.mSP -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/uins.mAddr -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/uins.mRegs -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/uins.mS2 -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/uins.ma -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/uins.mb -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/uins.wPC -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/uins.wSP -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/uins.wIR -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/uins.wAB -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/uins.wRalu -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/uins.wReg -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/uins.wnz -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/uins.wcv -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/uins.ce -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/uins.rw -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/uins.inst -radix hexadecimal}} -subitemconfig {/uc_r8_tb/MICROCONTROLADOR/R8/uins.mPC {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/uins.mSP {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/uins.mAddr {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/uins.mRegs {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/uins.mS2 {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/uins.ma {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/uins.mb {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/uins.wPC {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/uins.wSP {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/uins.wIR {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/uins.wAB {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/uins.wRalu {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/uins.wReg {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/uins.wnz {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/uins.wcv {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/uins.ce {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/uins.rw {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/uins.inst {-height 15 -radix hexadecimal}} /uc_r8_tb/MICROCONTROLADOR/R8/uins
add wave -noupdate -radix hexadecimal -childformat {{/uc_r8_tb/MICROCONTROLADOR/R8/instruction(15) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/instruction(14) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/instruction(13) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/instruction(12) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/instruction(11) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/instruction(10) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/instruction(9) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/instruction(8) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/instruction(7) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/instruction(6) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/instruction(5) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/instruction(4) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/instruction(3) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/instruction(2) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/instruction(1) -radix hexadecimal} {/uc_r8_tb/MICROCONTROLADOR/R8/instruction(0) -radix hexadecimal}} -subitemconfig {/uc_r8_tb/MICROCONTROLADOR/R8/instruction(15) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/instruction(14) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/instruction(13) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/instruction(12) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/instruction(11) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/instruction(10) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/instruction(9) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/instruction(8) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/instruction(7) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/instruction(6) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/instruction(5) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/instruction(4) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/instruction(3) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/instruction(2) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/instruction(1) {-height 15 -radix hexadecimal} /uc_r8_tb/MICROCONTROLADOR/R8/instruction(0) {-height 15 -radix hexadecimal}} /uc_r8_tb/MICROCONTROLADOR/R8/instruction
add wave -noupdate -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/MEM/memoryArray
add wave -noupdate -divider Memory
add wave -noupdate -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/MEM/clk
add wave -noupdate -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/MEM/ce_n
add wave -noupdate -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/MEM/we_n
add wave -noupdate -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/MEM/oe_n
add wave -noupdate -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/MEM/address
add wave -noupdate -radix hexadecimal /uc_r8_tb/MICROCONTROLADOR/MEM/data
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {184323711 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {346500 ns}
